# Generated by Django 5.2.1 on 2026-02-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0002_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
